# Generated by Django 5.1.1 on 2025-04-23 19:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stdapp', '0002_teacher'),
    ]

    operations = [
        migrations.CreateModel(
            name='Time',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.CharField(max_length=250)),
                ('end', models.CharField(max_length=250)),
                ('classs', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='stdapp.class')),
            ],
        ),
    ]
