# Generated by Django 5.1.1 on 2025-04-24 04:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stdapp', '0003_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=250)),
                ('lname', models.CharField(max_length=250)),
                ('phno', models.IntegerField(max_length=12)),
                ('current_school', models.CharField(max_length=250)),
                ('image', models.ImageField(upload_to='profile/')),
                ('classs', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='stdapp.class')),
            ],
        ),
    ]
