# Generated by Django 5.1.1 on 2025-04-24 06:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stdapp', '0005_gender_student_gender'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gender',
            old_name='men',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='gender',
            name='women',
        ),
    ]
