# Generated by Django 5.1.1 on 2025-04-27 14:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stdapp', '0006_rename_men_gender_name_remove_gender_women'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('status', models.CharField(choices=[('present', 'Present'), ('absent', 'Absent')], default='present', max_length=10)),
                ('classs', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stdapp.class')),
                ('marked_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='stdapp.teacher')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stdapp.student')),
            ],
            options={
                'unique_together': {('student', 'classs', 'date')},
            },
        ),
    ]
