# Generated by Django 5.2 on 2025-05-09 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stdapp', '0007_attendance'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='teacher_photos/'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='sslc_certificate',
            field=models.FileField(blank=True, null=True, upload_to='teacher_certificates/'),
        ),
    ]
