# Generated by Django 5.2 on 2025-05-15 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stdapp', '0008_teacher_photo_teacher_sslc_certificate'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
